### ISSUE TITLE
pwa:create:sw command puts sw.js file in project root directory

### ISSUE THREAD

**Issue by davidromani** [Spomky-Labs/phpwa#101]
### Version(s) affected

1.0.5

### Description

I've executed `symfony console pwa:create:sw` command described [here](https://pwa.spomky-labs.com/the-service-worker/workbox/service-worker-creation) and it created a sw.js file into my project root folder.

### How to reproduce

Do the same procedure in described in de description section and you don't get sw.js file located inside `assets` directory

**Comment by tacman** [comment]
Do you have symfony/asset-mapper installed and enabled in bundles.php?

**Comment by Spomky** [comment]
My mistake. I made bad changes. Should be fixed with `1.0.6`

**Comment by davidromani** [comment]
Ok, thanks

**Comment by Spomky** [comment]
In the first days of the bundle, this command was a bit more complex.
Now it only creates a copy of an empty file.
I will remove this command and explain you just need to create a file in `assets/sw.sj` and put your application logic and/or let the bundle populate it with cache rules.

**Comment by Spomky** [comment]
Command removed in 1.1.x
