### ISSUE TITLE
All Caches should implement CacheInterface, any maybe CacheTrait

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#105]
### Description

I'm working on the debug toolbar, and I'd like to display a table of the caches.

All of them implement some similar properties, having them implement an interface would make them easy to find.  

We could add getters to a trait, too.  No compelling reason yet to do so, but maybe someday.

### Example

```php
        foreach ($this->getWorkbox() as $var=>$val) {
            if (is_object($val)) {
                $name = $val::class;
                if (str_ends_with($name, 'Cache')) {
                    $cache[] = (array)$val + ['name' => (new \ReflectionClass($name))->getShortName()];
                }
            }
        }
```

Rather than checking if the class ends in Cache, I'd rather check for an interface.

Final result I think will be helpful

![image](https://github.com/Spomky-Labs/pwa-bundle/assets/619585/dc6d09d8-ba46-43de-bf60-55d50ac4f324)

**Comment by Spomky** [comment]
That's really nice!
OK for a CacheInterface. at least with the name and strategy.
It could be more generic in the future.

**Comment by tacman** [comment]
Thanks!  I'm going to add more to the toolbar today (e.g. manifest).

I see the different caches, but I don't see the Cache Strategy.  Am I missing something?

**Comment by Spomky** [comment]
Resolved the the `HasCacheStratigies` interface.
