### ISSUE TITLE
icons command produces invalid yaml file

### ISSUE THREAD

**Issue by Spomky** [Spomky-Labs/phpwa#106]
### Version(s) affected

1.0.x

### Description

As mentioned here: https://github.com/Spomky-Labs/pwa-bundle/discussions/100#discussioncomment-8693164
The command output should be verified

### How to reproduce

Execute the command

**Comment by Spomky** [comment]
Actually, this is normal as the icons can be used in various sections.
I added a comment after the command is executed

**Comment by tacman** [comment]
FWIW, the yaml is still incorrect (but valid), it should be type: not format:
