### ISSUE TITLE
Prefetch pages on-demand

### ISSUE THREAD

**Issue by Spomky** [Spomky-Labs/phpwa#117]
### Description

As Workbox Window instance is available globally, it could be great to ask prefecting Urls just by sending Urls front the frontend

```js
// From the frontend
window.workbox.messageSW({"type": "PREFETCH", "payload": {"urls": ["/foo", "/bar"]}}); });

//From the SW
async function fetchAsync(url) {
  await fetch(url);
}

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'PREFETCH') {
    const urls = event.data.payload.urls;
    for (let i in urls) {
      fetchAsync(urls[i]);
    }
  }
});
```

**Comment by tacman** [comment]
Don't some of the caching strategies automatically include prefetch?  I'm thinking of CacheOnly at least, but maybe some of the others.

Although I don't follow this completely, it would be nice to have something like this that the user can configure with Symfony only, probably as event (e.g. #113 )

I'm thinking of a bundle summary like "Make your Symfony+Stimulus/Assetmapper application available as a PWA without writing a single new line of Javascript!"

**Comment by Spomky** [comment]
> Don't some of the caching strategies automatically include prefetch?
> [...] Although I don't follow this completely

The urls given in the config are those for significant features the users will certainly go i.e. key features. These pages must be available offline or served very quickly for the best UX

What I have in mind is slightly different. The user arrives on a page and this page has relationships with other resources.
As an example, a science article about quantic computing may be linked to 3 of the most view related articles.
The user may click on those related articles and you want to serve them as quickly as possible or the user may read them later and you want to serve them when offline.
In this case, you can ask the SW to prefetch those pages.

**Comment by Spomky** [comment]
> I'm thinking of a bundle summary like "Make your Symfony+Stimulus/Assetmapper application available as a PWA without writing a single new line of Javascript!"

Another suggestion: write JS? I did this before.

**Comment by tacman** [comment]
> Another suggestion: write JS? I did this before.

Sorry, I don't follow.

**Comment by Spomky** [comment]
For the bundle summary

**Comment by tacman** [comment]
> the user may read them later and you want to serve them when offline.

Ah, that makes sense.  Symfony has [something like that for regular web browsing](https://symfony.com/doc/current/web_link.html#:~:text=Symfony%20provides%20native%20support%20(via%20the%20WebLink%20component)%20for%20managing%20Link&text=prefetch()%20:%20%22identifies%20a%20resource%20that%20might%20be), but of course that's at the page level, not dynamic/on-demand, as this issue describes.

**Comment by tacman** [comment]
> For the bundle summary

Still don't follow.  What's the bundle summary that you're thinking of?  

For me, the HUGE feature of this bundle is that you don't have to learn the intricacies of the service worker and manifest.   The first big problem you've solved is leveraging AssetMapper, and now the myriad of ways the requests can cached.  But to do it without additional javascript, wow, that's something!

**Comment by Spomky** [comment]
Feature added. With a stimulus controller!

```twig
    <link rel="prefetch" href="{{ path('article2') }}"> 
    <link rel="prefetch" href="{{ path('article3') }}">
    <div {{ stimulus_controller('@pwa/prefetch-on-demand') }}>
        <span {{ stimulus_action(
            '@pwa/prefetch-on-demand',
            'prefetch',
            'mouseover',
            {urls: [path('article4'), path('article5')]}
        )}}
        >On demand prefetch</span>
    </div>
```

> But to do it without additional javascript, wow, that's something!

Indeed, this is the key point of this bundle and in the same way of thinking about Symfony UX in general.
Back in December I chatted with Ryan Weather, we both agree that managing JS is boring. Nobody wants to do that.
