### ISSUE TITLE
Making CachingStrategy available in Cache

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#118]
### Description

I'd like to add the caching strategy to the debug toolbar, I think it's one of the most critical pieces of information.  Related to #117  and #113

![image](https://github.com/Spomky-Labs/pwa-bundle/assets/619585/fcbc6cd0-d295-477a-9d79-54dc4a6d25a3)

### Example

Perhaps when we implement the CacheInterface with the common methods, we could add a getCacheStrategy().  But I could be completely wrong about where the strategy is defined.

**Comment by Spomky** [comment]
Hi @tacman,

I've just push an update that may solve your problem.
The way the SW Compiler works has been reviewed. Now it iterates over a list of rules. It will be simpler to add rules in the future.

Also, I created a new interface `SpomkyLabs\PwaBundle\Service\HasCacheStrategies` and service that have this interface have the tag `spomky_labs_pwa.cache_strategy`.
This means you can iterate over this tag to get all cache strategies used in an application.

```php
<?php

declare(strict_types=1);

namespace Acme;

use SpomkyLabs\PwaBundle\Service\HasCacheStrategies;

final readonly class ListCacheStrategies
{
    /**
     * @param iterable<HasCacheStrategies> $cacheStrategyServices
     */
    public function __construct(
        #[TaggedIterator('spomky_labs_pwa.cache_strategy')]
        private iterable $cacheStrategyServices,
    ) {
    }

    public function doWhatYouWant(): array
    {
        foreach($this->cacheStrategyServices as $service) {
            $strategies = $service->getCacheStrategies();
            ///
        }
    }
}
```

**Comment by Spomky** [comment]
Note that warm cache Urls are not yet managed.
Let me know if you see other fields to add to the `options` property.

**Comment by Spomky** [comment]
I created a command to demonstrate how it works:

```sh
symfony console pwa:cache:list-strategies
```

**Comment by tacman** [comment]
Awesome!   I'll integrate it now.

**Comment by Spomky** [comment]
Hi,

The URLs and plugins are now part of the returned data.
I think you will be able to build a very detailed table now.
Just ask if you need other data.

Regards.

**Comment by tacman** [comment]
Thanks!

I hope to have something soon, this is more complicated than I'd hoped, but I think is going to be helpful to anyone working with the bundle.

The debug toolbar is already pointing out an issue.  The planet pages never changes, but the voyages do. So I want to serve the cached planet page, and make a turbo/stimulus/ajax call to /planet/3/_voyages to get the html snippet showing the voyage, which has a different cache strategy.

Or I could make an ajax call to get json or jsonld data, which might not have the appropriate extension, but will have a mime-type in the Response and of course will match /api.

I should have something to show soon.  What do you think about an EventListener to populate the cacheStrategy and preload pages?

**Comment by Spomky** [comment]
Yesterday I was thinking about a way to serve pages with different caching strategies. I implement that only for the purge_cache that is intended to by used when navigating.
I will change that soon to all different caching type depending on a regex

**Comment by tacman** [comment]
I've updated the toolbar in pwa-extra to show all the caches, not just the ones with warmUrls.  There's too many tabs, though, I'm not sure how to best organize these.

![image](https://github.com/Spomky-Labs/pwa-bundle/assets/619585/4c39b003-53ff-479b-b05e-2944abf7e67a)

cF=cacheFirst, nO=networkOnly, etc.   The number in the badge is the warm cache count.
