### ISSUE TITLE
Add a debug toolbar

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#128]
### Description

pwa extra bundle has a debug toolbar, I'll continue to develop it until it's ready to be moved into this bundle.  We can use this issue for discussion, though, previous it was a comment in #118 .  Two issues where the debug toolbar will be very helpful, #113  and configuring the cache based in a PHP attribute.

### Example

```bash
git clone git@github.com:tacman/phpwa-demo.git && cd phpwa-demo
git checkout with-debug-toolbar
composer install
echo "DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db" > .env.local
bin/console d:schema:update --force --complete
bin/console tailwind:build
symfony server:start -d
symfony open:local
```

![image](https://github.com/Spomky-Labs/pwa-bundle/assets/619585/1c1e27cd-4729-45fb-a9b1-0baea9e1dcee)

**Comment by tacman** [comment]
I cleaned up the debug panel to group everything by class.  I think it's a bit cleaner and can handle more strategies now.

![image](https://github.com/Spomky-Labs/pwa-bundle/assets/619585/8ffee496-a90b-4806-9431-0cd828d41687)

**Comment by Spomky** [comment]
Done and merged.
Will be enhanced as the bundle evolves.
