### ISSUE TITLE
Warning message: Dto\ResourceCache" class is considered final.

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#170]
### Version(s) affected

1.2.x

### Description

  1x: The "SpomkyLabs\PwaBundle\Dto\ResourceCache" class is considered final. It may change without further notice as of its next major version. You should not extend it from "SpomkyLabs\PwaBundle\Dto\PageCache".
    1x in AllRoutesTest::testRoutesDoNotReturnInternalError from App\Tests

### How to reproduce

I saw this when running phpunit in an application that uses the bundle.

### Possible Solution

remove final from Dto\ResourceCache"?

**Comment by Spomky** [comment]
Hi @tacman,

`ResourceCache` will replace `PageCache` That is final too. There is no reason to extend those classes are thay are used internaly and generated from the configuration (`resource_cache`).
You can safely ignore this warning as long as you do not extend it.

**Comment by tacman** [comment]
Right, but the deprecation messages are showing up in the logs.  Since PageCache does extend ResourceCache, it shouldn't be marked as final, right?

[Application] May 10 15:20:10 |INFO   | DEPREC User Deprecated: The "SpomkyLabs\PwaBundle\Dto\ResourceCache" class is considered final. It may change without further notice as of its next major version. You should not extend it from "SpomkyLabs\PwaBundle\Dto\PageCache". 
[Application] May 10 15:20:10 |INFO   | DEPREC User Deprecated: The "SpomkyLabs\PwaBu

**Comment by tacman** [comment]
appears to be fixed in 1.3.x

**Comment by Spomky** [comment]
Was used by [Dto/PageCache](https://github.com/Spomky-Labs/pwa-bundle/blob/7dd44c2077143824e4e1c412c50853155a8f9c7f/src/Dto/PageCache.php#L9) that is now deprecated and not used anymore from the bundle.
