### ISSUE TITLE
Strict MIME type checking error with workbox

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#217]
### Version(s) affected

1.2

### Description

I get the following error _on production_ but not in dev

failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

### How to reproduce

Look at the console log in https://noise.survos.com/

Repo is at https://github.com/survos-sites/noise, but running in dev it works okay, and it even works okay running in prod locally.  

### Possible Solution

The error is here:

```js
<script type="module" >
  import {Workbox} from '/workbox/workbox-window.prod.mjs';
  if ('serviceWorker' in navigator) {
    const wb = new Workbox('/sw.js', {scope: '/', useCache: true});
    wb.register();
    window.workbox = wb;
  }
</script>
```

Perhaps related to skip_waiting?  

### Additional Context

This was the first project I did with pwa-bundle, from 1.0, so it's possible that pwa.yaml isn't configured to 1.2 standards.

![image](https://github.com/Spomky-Labs/pwa-bundle/assets/619585/c468dfd0-e0e9-4615-8515-4c4156bfdf35)

**Comment by Spomky** [comment]
Hi,

I got a similar issue in the past with nginx.
This can be fixed from the server config. See https://github.com/storybookjs/storybook/issues/20157#issuecomment-1348881515 for example.

**Comment by tacman** [comment]
Indeed, that worked, thanks!

I wonder if the docs could have a section called "Troubleshooting" which included these kind of issues.
