### ISSUE TITLE
can't autowire $imageProcessor

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#43]
### Version(s) affected

1.0-dev

### Description

Can't install

Cannot autowire service "SpomkyLabs\PwaBundle\Command\CreateIconsCommand":   
!!    argument "$imageProcessor

### How to reproduce

composer require Spomky-Labs/phpwa
./composer.json has been updated
Running composer update spomky-labs/phpwa
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking spomky-labs/phpwa (1.0.x-dev 89c8992)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing spomky-labs/phpwa (1.0.x-dev 89c8992): Extracting archive
Generating autoload files
113 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Symfony operations: 1 recipe (157135572b17d2b5d8d523f4d94c12ba)
  - Configuring spomky-labs/phpwa (>=1.0.x-dev): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In DefinitionErrorExceptionPass.php line 48:
!!                                                                                 
!!    Cannot autowire service "SpomkyLabs\PwaBundle\Command\CreateIconsCommand":   
!!    argument "$imageProcessor" of method "__construct()" references interface "  
!!    SpomkyLabs\PwaBundle\ImageProcessor\ImageProcessor" but no such service exi  
!!    sts. You should maybe alias this interface to one of these existing service  
!!    s: "SpomkyLabs\PwaBundle\ImageProcessor\ImagickImageProcessor", "SpomkyLabs  
!!    \PwaBundle\ImageProcessor\GDImageProcessor".                                 
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd

**Comment by Spomky** [comment]
Indeed. This should be fixed in the last version

**Comment by tacman** [comment]
yep, installs now, thanks!
