### ISSUE TITLE
Default favicon and other platform icons

### ISSUE THREAD

**Issue by Spomky** [Spomky-Labs/phpwa#66]
What do you think of having a default favicon in the bundle, with instructions on how to customize?  It seems like the first error I always get is favicon failing.

_Originally posted by @tacman in https://github.com/Spomky-Labs/phpwa/issues/45#issuecomment-1916674830_

**Comment by Spomky** [comment]
Seems legit to me. It is boring to set icons at the correct size/format for all platforms.
The Twig function could help to generate the following HTML directives:

```html
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon"href="/favicon.ico">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="/mstile-144x144.png">
```

**Comment by tacman** [comment]
Yes, a twig function or maybe even a twig component.

I was looking at https://github.com/genkgo/favicon, but it [doesn't work with php 8.3 yet](https://github.com/genkgo/favicon/issues/3).

**Comment by Spomky** [comment]
> Yes, a twig function or maybe even a twig component.

This can be managed by the `pwa()` command that is already managing the Manifest file, the service worker or some html attributes.

**Comment by Spomky** [comment]
Complete HTML to write. Corresponds to best known possibilities to cover as much as systems as possible

```html
<link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="194x194" href="/favicons/favicon-194x194.png">
<link rel="icon" type="image/png" sizes="192x192" href="/favicons/android-chrome-192x192.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png">
<link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="{{ ---- BAR COLOR HERE }}">
<meta name="apple-mobile-web-app-title" content="{{ ---- APP NAME HERE }}">
<meta name="application-name" content="{{ ---- APP NAME HERE }}">
<meta name="msapplication-TileColor" content="{{ ---- TILE COLOR HERE }}">
<meta name="msapplication-TileImage" content="/favicons/mstile-144x144.png">
```

List of assets to generate:
* Android
    * /favicons/android-chrome-36x36.png
    * /favicons/android-chrome-48x48.png
    * /favicons/android-chrome-72x72.png
    * /favicons/android-chrome-96x96.png
    * /favicons/android-chrome-144x144.png
    * /favicons/android-chrome-192x192.png
    * /favicons/android-chrome-256x256.png
    * /favicons/android-chrome-384x384.png
    * /favicons/android-chrome-512x512.png
* MacOS Safari
    * /favicons/safari-pinned-tab.svg
*  iOS (6+)
    * /favicons/apple-touch-icon.png
    * /favicons/apple-touch-icon-57x57.png
    * /favicons/apple-touch-icon-60x60.png
    * /favicons/apple-touch-icon-72x72.png
    * /favicons/apple-touch-icon-76x76.png
    * /favicons/apple-touch-icon-114x114.png
    * /favicons/apple-touch-icon-120x120.png
    * /favicons/apple-touch-icon-144x144.png
    * /favicons/apple-touch-icon-152x152.png
    * /favicons/apple-touch-icon-180x180.png
*  iOS precomposed (6+)
    * /favicons/apple-touch-icon-precomposed.png
    * /favicons/apple-touch-icon-57x57-precomposed.png
    * /favicons/apple-touch-icon-60x60-precomposed.png
    * /favicons/apple-touch-icon-72x72-precomposed.png
    * /favicons/apple-touch-icon-76x76-precomposed.png
    * /favicons/apple-touch-icon-114x114-precomposed.png
    * /favicons/apple-touch-icon-120x120-precomposed.png
    * /favicons/apple-touch-icon-144x144-precomposed.png
    * /favicons/apple-touch-icon-152x152-precomposed.png
    * /favicons/apple-touch-icon-180x180-precomposed.png
* Other
    * /favicons/favicon-16x16.png
    * /favicons/favicon-32x32.png
    * /favicons/favicon-194x194.png
* Windows Tiles
    * /favicons/browserconfig.xml
    * /favicons/mstile-70x70.png
    * /favicons/mstile-144x144.png
    * /favicons/mstile-150x150.png
    * /favicons/mstile-310x150.png
    * /favicons/mstile-310x310.png
* Generic
    * /favicon.ico

Content of `/favicons/browserconfig.xml`
```xml
<?xml version="1.0" encoding="utf-8"?>
<browserconfig>
    <msapplication>
        <tile>
            <square70x70logo src="/favicons/mstile-70x70.png"/>
            <square150x150logo src="/favicons/mstile-150x150.png"/>
            <square310x310logo src="/favicons/mstile-310x310.png"/>
            <wide310x150logo src="/favicons/mstile-310x150.png"/>
            <TileColor>{{ ---- TILE COLOR HERE }}</TileColor>
        </tile>
    </msapplication>
</browserconfig>

```

**Comment by Spomky** [comment]
Done
