### ISSUE TITLE
Changes in pwa.yaml needs Symfony cache clear to works well

### ISSUE THREAD

**Issue by davidromani** [Spomky-Labs/phpwa#99]
### Description

Changes into `pwa.yaml` config requires a Symfony's cache clear to works well.

I've tried to require this bundle into a brand new Symfony demo project and after I've installed, following [this page](https://pwa.spomky-labs.com/installation) rendering instructions, the `<link rel="manifest" href="/site.webmanifest">` HTML node doesn't appears until I've removed the Symfony's cache.

Maybe will be helpfull for others warns about to clears the cache, as a reminder, to save time looking for the missing manifest `<link rel="manifest" href="/site.webmanifest">` rendering...

I can provide a PR into doc repository with a warning if you wants.

**Comment by Spomky** [comment]
I updated the documentation pages.
This may be caused by the `enabled` configuration option that turns to `true` and has an impact on the Twig pages.

**Comment by davidromani** [comment]
Great! Many thanks!!
